[mysqld]
port            = 3307
character-set-server = utf8mb4
collation-server     = utf8mb4_unicode_ci
default-time-zone    = +08:00
require_secure_transport=OFF

[mysql]
default-character-set = utf8mb4

[client]
port    = 3307
host    = 127.0.0.1
